import type { TFile } from "obsidian";

/**
 * A trip is anything that needs planning around a date and a place — a
 * fortnight in Japan, a Saturday in Ghent, or doors-at-19:00 in Tilburg.
 */
export type TripKind = "holiday" | "city-break" | "day-trip" | "concert" | "event" | "business";

export type TripStatus = "current" | "upcoming" | "past";

/**
 * `event-details` is no longer created: a concert is a trip with one headline
 * activity, and having both meant the same venue and tickets could be recorded
 * in two places. The id stays so notes made by older versions still read.
 */
export type SubNoteId =
  | "itinerary"
  | "packing"
  | "accommodation"
  | "budget"
  | "food"
  | "event-details"
  | "transport";

export interface KindDef {
  id: TripKind;
  label: string;
  /** Lucide icon name, used in the sidebar and the kind picker. */
  icon: string;
  /** Single-day kinds hide the end-date field entirely; end === start. */
  singleDay: boolean;
  /** Pre-selected length in days when you pick this kind in the new-trip modal. */
  defaultDurationDays: number;
  /** Sub-notes generated by default. Overridable per kind in settings. */
  subNotes: SubNoteId[];
  /** Concerts and events have a venue; a fortnight in Japan does not. */
  hasVenue: boolean;
}

export const KINDS: readonly KindDef[] = [
  {
    id: "holiday",
    label: "Holiday",
    icon: "palmtree",
    singleDay: false,
    defaultDurationDays: 14,
    subNotes: ["itinerary", "packing", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
  {
    id: "city-break",
    label: "City break",
    icon: "building-2",
    singleDay: false,
    defaultDurationDays: 3,
    subNotes: ["itinerary", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
  {
    id: "day-trip",
    label: "Day trip",
    icon: "sun",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "food"],
    hasVenue: false,
  },
  {
    id: "concert",
    label: "Concert",
    icon: "music",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "transport", "food"],
    hasVenue: true,
  },
  {
    id: "event",
    label: "Event",
    icon: "ticket",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "transport", "food"],
    hasVenue: true,
  },
  {
    id: "business",
    label: "Business trip",
    icon: "briefcase",
    singleDay: false,
    defaultDurationDays: 3,
    subNotes: ["itinerary", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
];

const KIND_BY_ID = new Map(KINDS.map((k) => [k.id, k]));

export function kindDef(id: string | undefined): KindDef {
  return KIND_BY_ID.get((id ?? "") as TripKind) ?? KINDS[0];
}

export function isTripKind(value: unknown): value is TripKind {
  return typeof value === "string" && KIND_BY_ID.has(value as TripKind);
}

export const SUB_NOTE_LABELS: Record<SubNoteId, string> = {
  itinerary: "Itinerary",
  packing: "Packing List",
  accommodation: "Accommodation",
  budget: "Budget",
  food: "Food",
  "event-details": "Event Details",
  transport: "Transport",
};

/** A trip as read back out of the vault. */
export interface Trip {
  file: TFile;
  /** Folder holding the trip note and its sub-notes. */
  folderPath: string;
  title: string;
  kind: TripKind;
  country: string;
  city: string;
  venue: string;
  /** ISO YYYY-MM-DD. */
  startDate: string;
  /** ISO YYYY-MM-DD; equal to startDate for single-day kinds. */
  endDate: string;
  status: TripStatus;
  /** Who is going. Drives packing quantities and the per-person cost split. */
  travellers: string[];
  /** Where you are leaving from — a trip has two ends, not one. */
  originCity: string;
  originAirport: string;
  /** Budget for the whole trip, or null when none was set. */
  budgetTotal: number | null;
}

/** The form payload shared by the new-trip and edit-trip modals. */
export interface TripDraft {
  title: string;
  kind: TripKind;
  country: string;
  city: string;
  venue: string;
  startDate: string;
  endDate: string;
  notes: string;
  subNotes: SubNoteId[];
  travellers: string[];
  originCity: string;
  originAirport: string;
  /** Budget for the whole trip, asked once and reused everywhere. */
  budgetTotal: number | null;
}

export interface TravelPlannerSettings {
  /** Root folder holding every trip. */
  tripsFolder: string;
  /**
   * Folder name for a trip, relative to tripsFolder. Supports {year}, {month},
   * {start}, {end}, {title}, {city}, {country}, {kind}. Defaults to grouping by
   * year with a date prefix so a second visit to Tokyo doesn't collide with the
   * first — the 1.x layout used the bare destination and simply refused.
   */
  folderPattern: string;
  defaultCountry: string;
  defaultKind: TripKind;
  /** Per-kind sub-note selection, overriding KindDef.subNotes. */
  subNotesByKind: Record<TripKind, SubNoteId[]>;
  /** Emit a ```foodspot``` block in the Food sub-note. */
  foodSpotEnabled: boolean;
  /** Which Food Spot view the generated block requests. */
  foodSpotView: "cards" | "list" | "table" | "shortlist";
  /** Ask before deleting a trip. Off means the confirm modal is skipped. */
  confirmDelete: boolean;
  /** Show past trips in the sidebar. */
  showPastTrips: boolean;
  /** Currency used when a booking or trip doesn't name its own. */
  defaultCurrency: string;
  /** Subfolder inside a trip where booking and expense notes live. */
  bookingsFolder: string;
  /** Subfolder inside a trip where attachments are copied. */
  attachmentsFolder: string;
  /**
   * Travel times call the Google Maps web services, which bill per request.
   * Off by default so nothing reaches the network — let alone the user's
   * billing account — until they switch it on and supply a key.
   */
  travelTimesEnabled: boolean;
  googleApiKey: string;
  /** Which modes to look up. Each mode is a separate billed request. */
  travelModes: TravelMode[];
  /** Airlines pinned to the top of the flight wizard picker. */
  starredAirlines: string[];
  /** Airports pinned to the top of the from/to pickers. */
  starredAirports: string[];
  /** Passports the party travels on, used for the visa check. */
  passportCountries: string[];
  /** Check Dutch government travel advice for the destination. */
  travelAdviceEnabled: boolean;
  /** Cost categories you added yourself, alongside the built-in ones. */
  customCategories: string[];
  /** Where you normally travel from, used to pre-fill the origin of a new trip. */
  homeCity: string;
  homeAirport: string;
  /** Everyone who might come along; a new trip starts with the first of these. */
  household: string[];
}

/** Google travel modes; duplicated here to keep the settings type dependency-free. */
export type TravelMode = "driving" | "transit" | "walking";

export const DEFAULT_SETTINGS: TravelPlannerSettings = {
  tripsFolder: "Trips",
  folderPattern: "{year}/{start} {title}",
  defaultCountry: "Netherlands",
  defaultKind: "holiday",
  subNotesByKind: KINDS.reduce(
    (acc, k) => {
      acc[k.id] = [...k.subNotes];
      return acc;
    },
    {} as Record<TripKind, SubNoteId[]>,
  ),
  foodSpotEnabled: true,
  foodSpotView: "cards",
  confirmDelete: true,
  showPastTrips: true,
  defaultCurrency: "EUR",
  bookingsFolder: "Bookings",
  attachmentsFolder: "Attachments",
  travelTimesEnabled: false,
  googleApiKey: "",
  travelModes: ["driving", "transit"],
  starredAirlines: [],
  starredAirports: [],
  passportCountries: ["Netherlands"],
  travelAdviceEnabled: true,
  customCategories: [],
  homeCity: "",
  homeAirport: "",
  household: [],
};

export const TRAVEL_VIEW_TYPE = "travel-planner-sidebar";
export const TRAVEL_DASHBOARD_TYPE = "travel-planner-dashboard";
export const FOODSPOT_PLUGIN_ID = "foodspot";
