import type { TFile } from "obsidian";

/**
 * A trip is anything that needs planning around a date and a place — a
 * fortnight in Japan, a Saturday in Ghent, or doors-at-19:00 in Tilburg.
 */
export type TripKind = "holiday" | "city-break" | "day-trip" | "concert" | "event" | "business";

export type TripStatus = "current" | "upcoming" | "past";

/**
 * Where a trip is in its life, which the calendar cannot tell you.
 *
 * `status` says where a trip sits relative to today; it has always been derived
 * from the dates and cannot distinguish "flights are booked" from "one of four
 * ideas for October" from "we called it off in May". Those are different things
 * to a planner, and only the traveller knows which is which — so this is stored,
 * not computed.
 */
export type TripStage = "planning" | "going" | "cancelled" | "went";

export interface StageDef {
  id: TripStage;
  label: string;
  /** Two words at most; this goes in a badge on a card. */
  badge: string;
  icon: string;
  /** Shown under the picker, so the difference between two stages is stated. */
  description: string;
  /**
   * Nothing is committed yet: the trip is a proposal being costed. Price
   * watching, the estimate and the "can we afford this" verdict live here.
   */
  provisional: boolean;
  /** It is not happening. Kept out of totals, counts and readiness. */
  dead: boolean;
}

/**
 * The order is the journey: an idea becomes a plan, a plan becomes a trip, a
 * trip becomes a memory — with cancelling as the exit that can happen at any
 * point. The pickers render them in this order.
 */
export const STAGES: readonly StageDef[] = [
  {
    id: "planning",
    label: "Planning",
    badge: "Planning",
    icon: "compass",
    description: "We want to go. Nothing is booked, and it might not happen.",
    provisional: true,
    dead: false,
  },
  {
    id: "going",
    label: "Going",
    badge: "Going",
    icon: "plane-takeoff",
    description: "It is happening. Booked, paid for, or committed to.",
    provisional: false,
    dead: false,
  },
  {
    id: "went",
    label: "Went",
    badge: "Went",
    icon: "flag",
    description: "We went. This one is history now.",
    provisional: false,
    dead: false,
  },
  {
    id: "cancelled",
    label: "Cancelled",
    badge: "Cancelled",
    icon: "circle-slash",
    description: "We planned it and called it off. Kept for the record.",
    provisional: false,
    dead: true,
  },
];

const STAGE_BY_ID = new Map(STAGES.map((s) => [s.id, s]));

export function stageDef(id: string | undefined): StageDef {
  return STAGE_BY_ID.get((id ?? "") as TripStage) ?? STAGES[0];
}

export function isTripStage(value: unknown): value is TripStage {
  return typeof value === "string" && STAGE_BY_ID.has(value as TripStage);
}

/**
 * `event-details` is no longer created: a concert is a trip with one headline
 * activity, and having both meant the same venue and tickets could be recorded
 * in two places. The id stays so notes made by older versions still read.
 */
export type SubNoteId =
  | "itinerary"
  | "packing"
  | "accommodation"
  | "budget"
  | "food"
  | "event-details"
  | "transport"
  | "prices";

export interface KindDef {
  id: TripKind;
  label: string;
  /** Lucide icon name, used in the sidebar and the kind picker. */
  icon: string;
  /** Single-day kinds hide the end-date field entirely; end === start. */
  singleDay: boolean;
  /** Pre-selected length in days when you pick this kind in the new-trip modal. */
  defaultDurationDays: number;
  /** Sub-notes generated by default. Overridable per kind in settings. */
  subNotes: SubNoteId[];
  /** Concerts and events have a venue; a fortnight in Japan does not. */
  hasVenue: boolean;
}

export const KINDS: readonly KindDef[] = [
  {
    id: "holiday",
    label: "Holiday",
    icon: "palmtree",
    singleDay: false,
    defaultDurationDays: 14,
    subNotes: ["itinerary", "packing", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
  {
    id: "city-break",
    label: "City break",
    icon: "building-2",
    singleDay: false,
    defaultDurationDays: 3,
    subNotes: ["itinerary", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
  {
    id: "day-trip",
    label: "Day trip",
    icon: "sun",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "food"],
    hasVenue: false,
  },
  {
    id: "concert",
    label: "Concert",
    icon: "music",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "transport", "food"],
    hasVenue: true,
  },
  {
    id: "event",
    label: "Event",
    icon: "ticket",
    singleDay: true,
    defaultDurationDays: 1,
    subNotes: ["itinerary", "transport", "food"],
    hasVenue: true,
  },
  {
    id: "business",
    label: "Business trip",
    icon: "briefcase",
    singleDay: false,
    defaultDurationDays: 3,
    subNotes: ["itinerary", "accommodation", "transport", "budget", "food"],
    hasVenue: false,
  },
];

const KIND_BY_ID = new Map(KINDS.map((k) => [k.id, k]));

export function kindDef(id: string | undefined): KindDef {
  return KIND_BY_ID.get((id ?? "") as TripKind) ?? KINDS[0];
}

export function isTripKind(value: unknown): value is TripKind {
  return typeof value === "string" && KIND_BY_ID.has(value as TripKind);
}

/**
 * Sub-notes a new trip can create.
 *
 * `event-details` is absent: a concert is a trip with one headline activity,
 * so the note is no longer generated. Its label stays in SUB_NOTE_LABELS so
 * notes made by older versions still read.
 */
export const CREATABLE_SUB_NOTES: SubNoteId[] = [
  "itinerary",
  "packing",
  "accommodation",
  "transport",
  "budget",
  "food",
  "prices",
];

export const SUB_NOTE_LABELS: Record<SubNoteId, string> = {
  itinerary: "Itinerary",
  packing: "Packing List",
  accommodation: "Accommodation",
  budget: "Budget",
  food: "Food",
  "event-details": "Event Details",
  transport: "Transport",
  prices: "Price Watch",
};

/**
 * One place a trip goes.
 *
 * A trip used to be a country and a city, which cannot describe going home →
 * Croatia → Montenegro → Italy → home. Stops are ordered, and the first is
 * still the trip's headline: the country and city fields carry it, so
 * everything that only needs one destination keeps working.
 */
export interface TripStop {
  country: string;
  city: string;
}

/** The stops of a trip, always at least one, oldest shape included. */
export function tripStops(trip: { stops?: TripStop[]; country: string; city: string }): TripStop[] {
  if (trip.stops && trip.stops.length > 0) return trip.stops;
  return [{ country: trip.country, city: trip.city }];
}

/** Every country a trip visits, in order, without repeats. */
export function tripCountries(trip: { stops?: TripStop[]; country: string; city: string }): string[] {
  const out: string[] = [];
  for (const stop of tripStops(trip)) {
    if (stop.country && !out.includes(stop.country)) out.push(stop.country);
  }
  return out;
}

/** Every city a trip visits, in order, without repeats. */
export function tripCities(trip: { stops?: TripStop[]; country: string; city: string }): string[] {
  const out: string[] = [];
  for (const stop of tripStops(trip)) {
    if (stop.city && !out.includes(stop.city)) out.push(stop.city);
  }
  return out;
}

/** "Dubrovnik & Kotor", or "Dubrovnik, Kotor & Split" — for titles and headings. */
export function joinPlaces(values: string[]): string {
  if (values.length === 0) return "";
  if (values.length === 1) return values[0];
  return `${values.slice(0, -1).join(", ")} & ${values[values.length - 1]}`;
}

/** Keys for the entry requirements a trip can tick off. */
export const entryKey = {
  visa: (country: string, passport: string) => `visa:${country}:${passport}`,
  extra: (country: string, name: string) => `extra:${country}:${name}`,
  checked: (country: string) => `checked:${country}`,
};

/** A trip as read back out of the vault. */
export interface Trip {
  file: TFile;
  /** Folder holding the trip note and its sub-notes. */
  folderPath: string;
  title: string;
  kind: TripKind;
  /** The first stop's country and city, kept for everything that needs one. */
  country: string;
  city: string;
  /** Every stop in order. One entry for a trip to a single place. */
  stops: TripStop[];
  venue: string;
  /** ISO YYYY-MM-DD. */
  startDate: string;
  /** ISO YYYY-MM-DD; equal to startDate for single-day kinds. */
  endDate: string;
  status: TripStatus;
  /**
   * Where the trip is in its life, with the passage of time already applied:
   * a trip you were going on, whose last day is behind you, reads as "went"
   * without anyone having to come back and say so.
   */
  stage: TripStage;
  /** What the note actually says, for the editor and the stage picker. */
  storedStage: TripStage;
  /** True when no note said, and the stage was guessed from the dates. */
  stageImplied: boolean;
  /** Who is going. Drives packing quantities and the per-person cost split. */
  travellers: string[];
  /** Where you are leaving from — a trip has two ends, not one. */
  originCity: string;
  originAirport: string;
  /** Budget for the whole trip, or null when none was set. */
  budgetTotal: number | null;
  /** Passports this trip is taken on. Empty falls back to the settings list. */
  passports: string[];
  /**
   * Entry requirements already dealt with, by key.
   *
   * A visa on arrival and an arrival card are work, and work gets finished.
   * Without somewhere to record that, the documents step could only ever stay
   * amber — it showed real tasks and offered no way to complete them.
   */
  entryDone: string[];
}

/** The form payload shared by the new-trip and edit-trip modals. */
export interface TripDraft {
  title: string;
  kind: TripKind;
  stage: TripStage;
  country: string;
  city: string;
  /** Every stop in order; the first is mirrored into country and city. */
  stops: TripStop[];
  venue: string;
  startDate: string;
  endDate: string;
  notes: string;
  subNotes: SubNoteId[];
  travellers: string[];
  originCity: string;
  originAirport: string;
  /** Budget for the whole trip, asked once and reused everywhere. */
  budgetTotal: number | null;
  passports: string[];
}

export interface AwtySettings {
  /** Root folder holding every trip. */
  tripsFolder: string;
  /**
   * Folder name for a trip, relative to tripsFolder. Supports {year}, {month},
   * {start}, {end}, {title}, {city}, {country}, {kind}. Defaults to grouping by
   * year with a date prefix so a second visit to Tokyo doesn't collide with the
   * first — the 1.x layout used the bare destination and simply refused.
   */
  folderPattern: string;
  defaultCountry: string;
  defaultKind: TripKind;
  /** Per-kind sub-note selection, overriding KindDef.subNotes. */
  subNotesByKind: Record<TripKind, SubNoteId[]>;
  /** Emit a ```foodspot``` block in the Food sub-note. */
  foodSpotEnabled: boolean;
  /** Which Food Spot view the generated block requests. */
  foodSpotView: "cards" | "list" | "table" | "shortlist";
  /** Ask before deleting a trip. Off means the confirm modal is skipped. */
  confirmDelete: boolean;
  /** Show past trips in the sidebar. */
  showPastTrips: boolean;
  /**
   * Show cancelled trips in the sidebar and on the Trips tab.
   *
   * On by default: a trip you called off is a record of a decision, and the
   * price watch that led to it is worth keeping. Turn it off once the list
   * gets long — the notes stay either way.
   */
  showCancelledTrips: boolean;
  /** Stage a new trip starts in. Most trips begin as an idea, not a booking. */
  defaultStage: TripStage;
  /** Currency used when a booking or trip doesn't name its own. */
  defaultCurrency: string;
  /** Subfolder inside a trip where booking and expense notes live. */
  bookingsFolder: string;
  /** Subfolder inside a trip where attachments are copied. */
  attachmentsFolder: string;
  /**
   * Travel times call the Google Maps web services, which bill per request.
   * Off by default so nothing reaches the network — let alone the user's
   * billing account — until they switch it on and supply a key.
   */
  travelTimesEnabled: boolean;
  googleApiKey: string;
  /** Which modes to look up. Each mode is a separate billed request. */
  travelModes: TravelMode[];
  /** Airlines pinned to the top of the flight wizard picker. */
  starredAirlines: string[];
  /** Airports pinned to the top of the from/to pickers. */
  starredAirports: string[];
  /** Passports the party travels on, used for the visa check. */
  passportCountries: string[];
  /** Check Dutch government travel advice for the destination. */
  travelAdviceEnabled: boolean;
  /** Cost categories you added yourself, alongside the built-in ones. */
  customCategories: string[];
  /** Where you normally travel from, used to pre-fill the origin of a new trip. */
  homeCity: string;
  homeAirport: string;
  /** Everyone who might come along; a new trip starts with the first of these. */
  household: string[];
}

/** Google travel modes; duplicated here to keep the settings type dependency-free. */
export type TravelMode = "driving" | "transit" | "walking";

export const DEFAULT_SETTINGS: AwtySettings = {
  tripsFolder: "Trips",
  folderPattern: "{year}/{start} {title}",
  defaultCountry: "Netherlands",
  defaultKind: "holiday",
  subNotesByKind: KINDS.reduce(
    (acc, k) => {
      acc[k.id] = [...k.subNotes];
      return acc;
    },
    {} as Record<TripKind, SubNoteId[]>,
  ),
  foodSpotEnabled: true,
  foodSpotView: "cards",
  confirmDelete: true,
  showPastTrips: true,
  showCancelledTrips: true,
  defaultStage: "planning",
  defaultCurrency: "EUR",
  bookingsFolder: "Bookings",
  attachmentsFolder: "Attachments",
  travelTimesEnabled: false,
  googleApiKey: "",
  travelModes: ["driving", "transit"],
  starredAirlines: [],
  starredAirports: [],
  passportCountries: ["Netherlands"],
  travelAdviceEnabled: true,
  customCategories: [],
  homeCity: "",
  homeAirport: "",
  household: [],
};

export const AWTY_SIDEBAR_TYPE = "awty-sidebar";
export const AWTY_DASHBOARD_TYPE = "awty-dashboard";
export const FOODSPOT_PLUGIN_ID = "foodspot";
